### ISSUE TITLE
Boundaries 

### ISSUE THREAD

**Issue by Kadi0** [TeamIndex3/WatershedSimulator#13]
The new terrain behave as if it's pouring the drops into the empty space. I'm sure that you've noticed that but I feel that this is crashing the simulation.

<img width="1680" alt="screen shot 2015-11-29 at 3 58 50 pm" src="https://cloud.githubusercontent.com/assets/14968599/11461180/e3fe6e6a-96b2-11e5-9c60-eccc64eee0ed.png">

**Comment by maxhkohl** [comment]
Majeed, 

Some of them end up flying behind the surface due to collision physics, and a very small amount fall through (probably less than 1 in 100, but this number can increase if the grid intersects or is below the surface).
I don't think this is a bug - it can be fixed by just moving the source around with the sliders and changing the velocity of the flow. I'll leave it up to you to decide whether or not to leave this bug open (and I can change the default starting location of the grid) or to just close it since it technically is working as intended.

**Comment by Kadi0** [comment]
I agree Max
Thx
